name: pokedex
description: Uma pokedex para etudo

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.1.0
  go_router: ^5.0.5
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.2
  intl: ^0.17.0
  json_annotation: ^4.7.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.5.0

flutter:
  uses-material-design: true
